# Default values for cb-apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
cbEnvionment: prod



ingress:
  hosts:
    - host: api-v2.careerboosts.com
      paths:
      - path: /cb-sr(/|$)(.*)
        backend:
          serviceName: cb-smart-recruitment-backend-svc
          servicePort: 8080
  tls:
  - secretName: tlscert
    hosts:
    - api-v2.careerboosts.com

app:
  webAppHost: sr-portal-v2.careerboosts.com
  keycloak:
    host: auth-b2c.careerboosts.com

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
