# Default values for cb-apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
cbEnvionment: dev

ingress:
  hosts:
    - host: api-v2-dev.careerboosts.com
      paths:
      - path: /cb-sr(/|$)(.*)
        backend:
          serviceName: cb-smart-recruitment-backend-svc
          servicePort: 8080
  tls:
  - secretName: tlscert
    hosts:
    - api-v2-dev.careerboosts.com

app:
  webAppHost: sr-portal-v2-dev.careerboosts.com
  keycloak:
    host: auth-b2c-dev.careerboosts.com


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.azure.com/scalesetpriority
          operator: In
          values:
          - spot

tolerations:
  - effect: NoSchedule
    key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: spot